### ISSUE TITLE
Possibly wrong theta_med estimation

### ISSUE THREAD

**Issue by sovrasov** [4uiiurz1/pytorch-adacos#4]
In the paper is stated that
![image](https://user-images.githubusercontent.com/5373517/58261078-506b3580-7d80-11e9-9ebc-bb68b526da66.png)

but in the code theta_med is computed as the median of all angles. I think we need to consider only angles of corresponding classes here.
https://github.com/4uiiurz1/pytorch-adacos/blob/7f7098598a6aba3dd682936fc1773391c30711e6/metrics.py#L33

**Comment by 4uiiurz1** [comment]
Thanks for letting me know!
I have fixed.
