### ISSUE TITLE
got lower acc than arcface or cosface on my own train&val dataset.

### ISSUE THREAD

**Issue by ykk648** [4uiiurz1/pytorch-adacos#8]
based on same params

**Comment by llf1234** [comment]
the same to you，did you fix this problem

**Comment by ykk648** [comment]
@llf1234 scale the code given is really bad for my own dataset, it looks like adacos only works on specific conditions if this repo implemented totally right.

**Comment by taekwan-lee** [comment]
@cloisonne I agree, experienced the same thing.

**Comment by ykk648** [comment]
no response for a long time

**Comment by lainxx** [comment]
I use adacos get higher map metrics than arcface in cub datasets
